# Generated by Django 2.2.6 on 2021-01-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default=None, null=True),
        ),
    ]
