# Generated by Django 2.2.6 on 2021-01-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210105_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.CharField(default=None, max_length=36)),
                ('name', models.CharField(default=None, max_length=36)),
                ('poster', models.ImageField(max_length=254, upload_to='posters')),
            ],
        ),
    ]
