# Generated by Django 2.2.6 on 2021-01-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='adminid',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movieid',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userid',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
